/*A subscriber, they are asked for the following information: 
  Name/Surname, VAT number, address, type of customer (Individual, 
  Professional, Company).
*/
CREATE TABLE CUSTOMER_TYPE(
    CTYPE_ID	NUMBER NOT NULL PRIMARY KEY,
    CTYPE_NAME	VARCHAR2(15) NOT NULL
);

CREATE TABLE CUSTOMER(
    CUSTOMER_ID			NUMBER NOT NULL PRIMARY KEY,
    CUSTOMER_NAME		VARCHAR2(20) NOT NULL,
    CUSTOMER_AFM		VARCHAR2(9) NOT NULL,
    CUSTOMER_ADDRESS	VARCHAR2(20) NOT NULL,
    CUSTOMER_TID	    NUMBER NOT NULL,
    CONSTRAINT C_T_FK FOREIGN KEY(CUSTOMER_TID)
        REFERENCES CUSTOMER_TYPE(CTYPE_ID)
);
/*Each connection has a phone number, activation date, 
  deactivation date if terminated and one of the following 
  usage plans: Small, Medium, Large, Extra Large. Each usage 
  plan has a fixed monthly fee, e.g., Small 10$, Medium 20$ etc.
*/
CREATE TABLE SUBSCRIPTION_PLAN(
    SPLAN_ID	NUMBER NOT NULL PRIMARY KEY,
    SPLAN_NAME	VARCHAR(15) NOT NULL,
    SPLAN_FIX	NUMBER NOT NULL
);
--Each customer can have one or more mobile connections.
CREATE TABLE SUBSCRIPTION(
    SUBSCRIPTION_ID				NUMBER NOT NULL PRIMARY KEY,
    SUBSCRIPTION_START_DATE		DATE NOT NULL,
    SUBSCRIPTION_END_DATE		DATE,
	SUBSCRIPTION_CID	        NUMBER NOT NULL,
	SUBSCRIPTION_NUMBER			VARCHAR2(10),
	CONSTRAINT S_C_FK FOREIGN KEY(SUBSCRIPTION_CID)
		REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE SUBS_PL_RELATION(
	REL_ID				NUMBER NOT NULL,
	SUBS_ID			    NUMBER NOT NULL,
	SUBS_PL_ID	        NUMBER NOT NULL,
    SUBS_PL_START_DATE  DATE NOT NULL,
    SUBS_PL_END_DATE	DATE,
	PRIMARY KEY(REL_ID, 
				SUBS_PL_START_DATE),
	CONSTRAINT R_S_FK FOREIGN KEY(SUBS_ID)
		REFERENCES SUBSCRIPTION(SUBSCRIPTION_ID),
	CONSTRAINT R_P_FK FOREIGN KEY(SUBS_PL_ID)
		REFERENCES SUBSCRIPTION_PLAN(SPLAN_ID)
);
/*Each customer's account has an account code, issue date, 
  account amount and outstanding account balance (e.g., if 
  the bill is $40 and the customer pays $25, the account 
  amount will be $40, and the outstanding balance will be 
  $15).
*/
CREATE SEQUENCE bill_seq 
	MINVALUE 		1
	INCREMENT BY	1
	START WITH 		8
;

CREATE TABLE BILLING(
    BILL_ID		NUMBER NOT NULL PRIMARY KEY DEFAULT bill_seq.NEXTVAL,
    BILL_DATE	DATE NOT NULL,
    BILL_AMOUNT NUMBER NOT NULL,
    BILL_REM	NUMBER NOT NULL,
    BILL_CID	NUMBER NOT NULL,
    BILL_SID    NUMBER NOT NULL,
	CONSTRAINT B_C_FK FOREIGN KEY(BILL_CID)
		REFERENCES CUSTOMER(CUSTOMER_ID),
	CONSTRAINT B_S_FK FOREIGN KEY(BILL_SID)
		REFERENCES SUBSCRIPTION(SUBSCRIPTION_ID)
);

SELECT * FROM CUSTOMER_TYPE;
SELECT * FROM CUSTOMER;
SELECT * FROM SUBSCRIPTION_PLAN;
SELECT * FROM SUBS_PL_RELATION;
SELECT * FROM SUBSCRIPTION;
SELECT * FROM BILLING;